version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: vulnerable_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: vulnerable_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend

  sql-injection:
    build:
      context: ./app/SQL
      dockerfile: Dockerfile
    container_name: sql_injection_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/vulnerable_db
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/SQL/static:/app/static
#      - ./app/xss/static:/app/xss/static
#      - ./app/csrf/static:/app/csrf/static
#      - ./app/file-upload/static:/app/file-upload/static
    ports:
      - "80:80"
    depends_on:
      - sql-injection
    networks:
      - backend

networks:
  backend:
    driver: bridge
